config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # rest url sales
   resources:sales

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sale.rb
class Sale < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  # chamada da view sales/index
  def index
    @sales = Sale.order(id: :desc)
    @saleContactsCount = Sale.where(status: 1).count()
    @saleContactsSumPrice = Sale.where(status: 1).sum(:price)
  end


  # Create new sale
  def create
    # render plain: params[:sales].inspect
    @sale = Sale.new sale_params
    @sale.save
    redirect_to '/sales'
  end


  private

  def sale_params
    params.require(:sale).permit([:name,:price,:status,:description])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunilVendas</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "main", media: "all" %>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <%= javascript_include_tag 'main', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>

app/views/sales/_sale.html.erb
<!--
<div class="row">
    <div class="col-md-2">
        <div class="card text-white bg-primary">
            <div class="card-body">
                <i><h5>Contato</h5></i>
            </div>
            <a class="card-footer text-white clearfix z-1" href="#">
                <i class="float-left">R$15.0000,000</i>
                <i class="float-right">2 Negócios</i>
            </a>
        </div>
        <div>
        <%- @sales.each do |sale| %>
            <div class="card sub-card">
                <div class="card-body">
                    <div class="mr-5"><%= sale.name %></div>
                </div>
                <div class="card-footer small">
                    <span class="float-right text-success">
                        R$ 5.000,00
                    </span>
                </div>
            </div>
            <% end  %>
        </div>
    </div>
</div> -->

app/views/sales/index.html.erb
<hr>
<div class="">
    <button id="new-contact" class="btn btn-primary "><img src="<%= image_path("icons/cash.png") %>" alt="Negócio" width="35"> Adicionar negócio</button>
</div>
<hr>

<div class="row">
    <div class="col-md-2">
        <div class="card text-white bg-primary">
            <div class="card-body">
                <i><h5>Contato</h5></i>
            </div>
            <div class="card-footer text-white clearfix z-1a">
                <i class="float-left">R$ <%= @saleContactsSumPrice %></i>
                <i class="float-right"><%= @saleContactsCount %> Negócios</i>
            </div>
        </div>
        <div>

            <!-- <img src="<%= image_path("icons/incheck.png") %>" width="20"> -->
            <div id='add-contact' style="display:none;">
                <div class="card sub-card">
                        <%= form_for:sale, :html => { :id => "form-sale" } ,url: sales_path do |f| %>
                        <%= f.hidden_field :status, :value => 1 %>
                    <div class="card-body">
                        <div class="mr-5">
                            <!-- <input class="form-card" type="text" id="name" name='name' placeholder="Titulo do Negócio"> -->
                            <%= f.text_field :name ,class:'form-card', placeholder: "Titulo do Negócio" %>
                            <span class="form-submit" id="submit">
                                <img  src="<%= image_path("icons/check.png") %>" width="22">
                            </span>
                            <span class="form-cancel">
                                <img id="cancel" src="<%= image_path("icons/incheck.png") %>" width="14">
                            </span>
                        </div>
                        <div class="mr-3">
                            <img src="<%= image_path("icons/compay.png") %>" width="20">
                            <%= f.text_field :description , class:'form-card', placeholder: "Nome do Cliente"%>
                        </div>
                    </div>
                    <div class="card-footer small">
                        <span class="float-right text-green">
                            R$ <%= f.text_field :price , class:'form-card form-card-cash', placeholder: "0,00"%>
                        </span>
                    </div>
                    <% end %>
                </div>
            </div>


            <%- @sales.each do |sale| %>
            <div class="card sub-card">
                <div class="card-body">
                    <div class="mr-5"><%= sale.name %></div>
                    <div class="mr-3"><img src="<%= image_path("icons/compay.png") %>" width="20"> <%= sale.description %></div>
                </div>
                <div class="card-footer small">
                    <span class="float-right text-green">
                        R$ <%= sale.price %>
                    </span>
                </div>
            </div>
            <% end  %>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card text-white bg-primary">
            <div class="card-body">
                <i><h5>Envio de Proposta</h5></i>
            </div>
            <div class="card-footer text-white clearfix z-1a">
                <i class="float-left">R$15.0000,000</i>
                <i class="float-right">2 Negócios</i>
            </div>
        </div>
        <div>
            <div class="card sub-card">
                <div class="card-body">
                    <div class="mr-5">TESTE</div>
                    <div class="mr-3">TESTE</div>
                </div>
                <div class="card-footer small">
                    <span class="float-right text-green">
                        R$ 5.000,00
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card text-white bg-primary">
            <div class="card-body">
                <i><h5>Fallow-up</h5></i>
            </div>
            <div class="card-footer text-white clearfix z-1a">
                <i class="float-left">R$15.0000,000</i>
                <i class="float-right">2 Negócios</i>
            </div>
        </div>
        <div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card text-white bg-primary">
            <div class="card-body">
                <i><h5>Fechamento</h5></i>
            </div>
            <div class="card-footer text-white clearfix z-1a">
                <i class="float-left">R$15.0000,000</i>
                <i class="float-right">2 Negócios</i>
            </div>
        </div>
        <div>
            <div class="card sub-card">
                <div class="card-body">
                    <div class="mr-5">Manutenção</div>
                    <div class="mr-3">Confeitaria</div>
                </div>
                <div class="card-footer small">
                    <span class="float-right text-green">
                        R$ 5.000,00
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card text-white bg-success">
            <div class="card-body">
                <i><h5>Ganhos</h5></i>
            </div>
            <div class="card-footer text-white clearfix z-1a">
                <i class="float-left">R$15.0000,000</i>
                <i class="float-right">2 Negócios</i>
            </div>
        </div>
        <div>
        </div>
    </div>
    <div class="col-md-2">
        <div class="card text-white bg-danger">
            <div class="card-body">
                <i><h5>Perdidos</h5></i>
            </div>
            <div class="card-footer text-white clearfix z-1a">
                <i class="float-left">R$15.0000,000</i>
                <i class="float-right">2 Negócios</i>
            </div>
        </div>
        <div>
        </div>
    </div>
</div>
</div>